plugins {
	id 'java'
	id 'application'
}

repositories {
	mavenCentral()
}

dependencies {
  compileOnly "com.diffblue.cover:cover-annotations:1.6.0"

	implementation project(':proguard-core')
	implementation project(':proguard-core-android')

	testImplementation "com.diffblue.cover:cover-annotations:1.6.0"
	testImplementation "org.junit.jupiter:junit-jupiter-engine:5.13.4"
	testImplementation "org.junit.vintage:junit-vintage-engine:5.11.3"
	testImplementation "org.mockito:mockito-core:5.19.0"
	testImplementation "org.mockito:mockito-junit-jupiter:5.19.0"
}

java {
	toolchain {
		languageVersion.set(JavaLanguageVersion.of(11))
	}

	withSourcesJar()
	withJavadocJar()
}
